services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: beuni_gifts_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.15-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/beuni_gifts_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    stdin_open: true
    tty: true

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/beuni_gifts_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data:
  bundle_cache: